services:
  server:
    container_name: server
    build: server
    volumes:
      - ./server:/usr/local/ccf355/server
    working_dir: /usr/local/ccf355/server
    network_mode: host

  client-julia:
    container_name: client-julia
    build: client
    environment:
      - DISPLAY=$DISPLAY
      - CLIENT_NAME=Julia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./client:/usr/local/ccf355/client
    working_dir: /usr/local/ccf355/client
    network_mode: host

  client-claudio:
    container_name: client-claudio
    build: client
    environment:
      - DISPLAY=$DISPLAY
      - CLIENT_NAME=Claudio
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./client:/usr/local/ccf355/client
    working_dir: /usr/local/ccf355/client
    network_mode: host
