services:
  database-server:
    container_name: db-server
    build: db-server
    volumes:
      - ./db-server:/usr/local/ccf355/db-server
    working_dir: /usr/local/ccf355/db-server
    network_mode: host

  application-server:
    container_name: app-server
    build: app-server
    volumes:
      - ./app-server:/usr/local/ccf355/app-server
    working_dir: /usr/local/ccf355/app-server
    network_mode: host

  client-jogador1:
    container_name: client-jogador1
    build: client
    environment:
      - DISPLAY=$DISPLAY
      - CLIENT_NAME=Julia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./client:/usr/local/ccf355/client
    working_dir: /usr/local/ccf355/client
    network_mode: host

  # client-jogador2:
  #   container_name: client-jogador2
  #   build: client
  #   environment:
  #     - DISPLAY=$DISPLAY
  #     - CLIENT_NAME=Claudio
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - ./client:/usr/local/ccf355/client
  #   working_dir: /usr/local/ccf355/client
  #   network_mode: host

  # client-jogador3:
  #     container_name: client-jogador3
  #     build: client
  #     environment:
  #       - DISPLAY=$DISPLAY
  #       - CLIENT_NAME=Claudio
  #     volumes:
  #       - /tmp/.X11-unix:/tmp/.X11-unix
  #       - ./client:/usr/local/ccf355/client
  #     working_dir: /usr/local/ccf355/client
  #     network_mode: host